cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),

    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

djangosite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from orders.views import stripe_webhook_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from main.views import basket_add, product_list, basket_remove


app_name = 'main'

urlpatterns = [

    path('', views.home_page, name='home_page'),

    path('product_list', product_list, name='product_list'),

    path('category/<int:category_id>/', product_list, name='category'),

    path('baskets/add/<int:product_id>/', basket_add, name='basket_add'),

    path('baskets/remove/<int:basket_id>/', basket_remove, name='basket_remove'),

    path('<int:id>/<slug:slug_category>/', views.product_list,
         name='product_list_by_category'),

    path('<int:id>/<slug:slug>', views.product_detail,
         name='product_detail'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from main.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "main/product/base.html" %}
{% load static %}

{% block title %}
    Корзина покупок
{% endblock %}

{% block content %}
    <h1>Корзина покупок</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Картинка</th>
            <th>Товар</th>
            <th>Обновить кол-во</th>
            <th>Удалить</th>
            <th>Кол-во</th>
            <th>Цена за шт</th>
            <th>Общая стоимость</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="
                                    {% if product.image_product %}{{ product.image_product.url }}{% else %}{% static 'img/flower.png' %}{% endif %}">
                        </a>
                    </td>
                    <td>{{ product.name_product }}</td>
                    <td>
                        <form action="{% url 'cart:cart_add' product.id %}" method="post">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.update }}
                            <input type="submit" value="Обновить">
                            {% csrf_token %}
                        </form>
                    </td>
                    <td><a href="{% url 'cart:cart_remove' product.id %}">Удалить</a></td>
                    <td>
                        {{ item.quantity }}
                    </td>
                    <td class="num">${{ item.price_product }}</td>
                    <td class="num">${{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Всего</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'main:product_list' %}" class="button light">В магазин</a>
        <a href="#" class="button">Оформить заказ</a>
    </p>
{% endblock %}