cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),

    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

djangosite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from orders.views import stripe_webhook_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from main.views import basket_add, product_list, basket_remove


app_name = 'main'

urlpatterns = [

    path('', views.home_page, name='home_page'),

    path('product_list', product_list, name='product_list'),

    path('category/<int:category_id>/', product_list, name='category'),

    path('baskets/add/<int:product_id>/', basket_add, name='basket_add'),

    path('baskets/remove/<int:basket_id>/', basket_remove, name='basket_remove'),

    path('<int:id>/<slug:slug_category>/', views.product_list,
         name='product_list_by_category'),

    path('<int:id>/<slug:slug>', views.product_detail,
         name='product_detail'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from orders.views import OrderCreateView, SuccessTemplateView, CanceledTemplates, OrderListView, OrderDetailView


app_name = 'orders'

urlpatterns = [

    path('', OrderListView.as_view(), name='orders_list'),
    path('order-create/', OrderCreateView.as_view(), name='order_create'),
    path('order-success/', SuccessTemplateView.as_view(), name='order_success'),
    path('order_cancel/', CanceledTemplates.as_view(), name='order_cancel'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order'),




]

orders/models.py
from django.db import models
from users.models import User
from main.models import Basket

class Order(models.Model):
    CREATED = 0
    PAID = 1
    ON_WAY = 2
    DELIVERED = 3
    STATUSES = (
        (CREATED, 'Создан'),
        (PAID, 'Оплачен'),
        (ON_WAY, 'Передано в доставку'),
        (DELIVERED, 'Доставлен'),
    )



    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    email = models.EmailField(max_length=256)
    address = models.CharField(max_length=256)
    basket_history = models.JSONField(default=dict)
    created = models.DateTimeField(auto_now_add=True)
    status = models.SmallIntegerField(default=CREATED, choices=STATUSES)
    initiator = models.ForeignKey(to=User, on_delete=models.CASCADE)


    def __str__(self):
        return f'Order #{self.id}. {self.first_name} {self.last_name}'

    def update_after_payment(self):
        baskets = Basket.objects.filter(user=self.initiator)
        self.status = self.PAID
        self.basket_history = {
            'purchased_items': [basket.de_json() for basket in baskets],
            'total_sum': float(baskets.total_sum()),
        }
        baskets.delete()
        self.save()

orders/forms.py
from django import forms

from orders.models import Order

class OrderForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Иван'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Иванов'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'you@example.com'}))
    address = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Россия, Москва, ул. Мира, дом 6'}))


    class Meta:
        model = Order
        fields = ('first_name', 'last_name', 'email', 'address')

orders/views.py
from django.views.generic.edit import CreateView
from orders.forms import OrderForm
from django.urls import reverse_lazy, reverse
from django.views.generic.base import TemplateView
from django.http import HttpResponseRedirect
from http import HTTPStatus
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from main.models import Basket
from orders.models import Order
from django.views.generic.list import ListView
from common.views import TitleMixin
from django.views.generic.detail import DetailView


import stripe
from django.conf import settings

stripe.api_key = settings.STRIPE_SECRET_KEY


class SuccessTemplateView(TemplateView, TitleMixin):
    template_name = 'orders/success.html'
    title = 'Спасибо за покупку!'


class CanceledTemplates(TemplateView):
    template_name = 'orders/canceled.html'


class OrderListView(TitleMixin, ListView):
    template_name = 'orders/orders.html'
    title = 'Заказы'
    queryset = Order.objects.all()
    ordering = ('-created')


    def get_queryset(self):
        queryset = super(OrderListView, self).get_queryset()
        return queryset.filter(initiator=self.request.user)


class OrderDetailView(DetailView):
    template_name = 'orders/order.html'
    model = Order

    def get_context_data(self, **kwargs):
        context = super(OrderDetailView, self).get_context_data(**kwargs)
        context['title'] = f'Заказ №{self.object.id}'
        return context


class OrderCreateView(CreateView, TitleMixin):
    template_name = 'orders/order-create.html'
    form_class = OrderForm
    success_url = reverse_lazy('orders:order_create')
    title = 'Оформление заказа'

    def post(self, request, *args, **kwargs):
        super(OrderCreateView, self).post(request, *args, **kwargs)
        baskets = Basket.objects.filter(user=self.request.user)
        checkout_session = stripe.checkout.Session.create(
            line_items=baskets.stripe_products(),
            metadata={'order_id': self.object.id},
            mode='payment',
            success_url='{}{}'.format(settings.DOMAIN_NAME, reverse('orders:order_success')),
            cancel_url='{}{}'.format(settings.DOMAIN_NAME, reverse('orders:order_cancel')),
        )
        return HttpResponseRedirect(checkout_session.url, status=HTTPStatus.SEE_OTHER)

    def form_valid(self, form):
        form.instance.initiator = self.request.user
        return super(OrderCreateView, self).form_valid(form)


@csrf_exempt
def stripe_webhook_view(request):
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, settings.STRIPE_WEBHOOK_SECRET
        )
    except ValueError as e:

        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:

        return HttpResponse(status=400)

    if event['type'] == 'checkout.session.completed':
        session = event['data']['object']

        fulfill_order(session)

    return HttpResponse(status=200)


def fulfill_order(session):
    order_id = int(session.metadata.order_id)
    order = Order.objects.get(id=order_id)
    order.update_after_payment()

orders/templates/orders/canceled.html
<!DOCTYPE html>
<html>
<head>
  <title>Checkout canceled</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <section>
    <p>Forgot to add something to your cart? Shop around then come back to pay!</p>
  </section>
</body>
</html>

orders/templates/orders/order-create.html
<!doctype html>

{% extends "main/product/base.html" %}
{% load static %}
{% load humanize %}

{% block title %}
    Store shop
{% endblock %}


{% block content %}
    <section>
        <div class="container">
            <div class="py-5 text-center">
                <h1>Оформление заказа</h1>
            </div>
            <div class="row g-5">
                <div class="col-md-5 col-lg-4 order-md-last">
                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-primary">Корзина</span>
                        <span class="badge badge-primary badge-pill text-white">{{ baskets.total_quantity }}</span>
                    </h4>
                    <ul class="list-group mb-3">


                        {% for basket in baskets %}
                            <li class="list-group-item d-flex justify-content-between lh-sm">
                                <div>
                                    <h6 class="my-0">{{ basket.product.name_product }}</h6>
                                    <small class="text-muted">{{ basket.quantity }} шт.</small>
                                </div>
                                <span class="text-muted">{{ basket.sum|intcomma }} руб.</span>
                            </li>
                        {% endfor %}

                        <li class="list-group-item d-flex justify-content-between">
                            <span>Сумма к оплате</span>
                            <strong>{{ baskets.total_sum|intcomma }} руб.</strong>
                        </li>
                    </ul>
                </div>
                <div class="col-md-7 col-lg-8">
                    <h4 class="mb-3">Адрес доставки</h4>
                    <form action="{% url 'orders:order_create' %}" method="post">
                        {% csrf_token %}
                        <div class="row g-3">
                            <div class="col-sm-6">
                                <label for="{{ form.first_name.id_for_label }}" class="form-label">Имя</label>
                                {{ form.first_name }}
                            </div>

                            <div class="col-sm-6">
                                <label for="{{ form.last_name.id_for_label }}" class="form-label">Фамилия</label>
                                {{ form.last_name }}
                            </div>

                            <div class="col-12 mt-3">
                                <label for="{{ form.email.id_for_label }}" class="form-label">Адрес электронной
                                    почты</label>
                                {{ form.email }}
                            </div>

                            <div class="col-12 mt-3">
                                <label for="{{ form.email.address }}" class="form-label">Адрес</label>
                                {{ form.address }}
                            </div>

                        </div>

                        <hr class="my-4">

                        <button class="w-100 btn btn-primary btn-lg" type="submit">Продолжить</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

orders/templates/orders/order.html
{% extends "main/product/base.html" %}
{% load static %}
{% load humanize %}
<!doctype html>


{% block title %}
    Store shop
{% endblock %}

{% block content %}
    <section>
    <div class="container pt-5">
        <div class="text-center mt-5">
            <h1>Заказ №{{ object.id }}</h1>
            <div class="orders mt-5">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Название</th>
                        <th scope="col">Кол-во</th>
                        <th scope="col">Цена</th>
                        <th scope="col">Сумма</th>
                    </tr>
                    </thead>
                        <tbody>
                        {% for purchased_item in object.basket_history.purchased_items %}
                            <tr>
                                <th scope="row">
                                    {{ purchased_item.product_name }}
                                </th>
                                <td>{{ purchased_item.quantity }}</td>
                                <td>{{ purchased_item.price|intcomma }} руб.</td>
                                <td>{{ purchased_item.sum|intcomma }} руб.</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                </table>
                <p class="float-right h4 mt-3">Итого {{ object.basket_history.total_sum }} руб.</p>
            </div>
        </div>
    </div>
</section>


{% endblock %}

orders/templates/orders/orders.html
{% extends "main/product/base.html" %}
{% load static %}
{% load humanize %}
<!doctype html>



{% block title %}
    Store shop
{% endblock %}

{% block content %}
    <section>
        <div class="container pt-5">
            <div class="text-center mt-5">
                <h1>Заказы</h1>
                <div class="orders mt-5">
                    <table class="table">
                        <thead>
                        <tr class="table-light">
                            <th scope="col">#</th>
                            <th scope="col">Статус</th>
                            <th scope="col">Создан</th>
                            <th scope="col">Итого</th>
                            <th scope="col">Действие</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for order in object_list %}
                            <tr>
                                <th scope="row">{{ order.id }}</th>
                                <td>{{ order.get_status_display }}</td>
                                <td>{{ order.created|naturaltime }}</td>
                                <td>{{ order.basket_history.total_sum|intcomma }} руб.</td>
                                <td>
                                    <a href="{% url 'orders:order' order.id %}">просмотреть</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

orders/templates/orders/success.html
<!doctype html>

{% extends "main/product/base.html" %}
{% load static %}

{% block title %}
    Store shop
{% endblock %}


{% block content %}

        <nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
        <div class="container-fluid">

            {#            КНОПКА НАЗАД#}
            <a class="btn btn-dark mx-2 my-2" href="{% url 'main:home_page' %}" role="button">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-backspace-fill" viewBox="0 0 16 16">
                    <path d="M15.683 3a2 2 0 0 0-2-2h-7.08a2 2 0 0 0-1.519.698L.241 7.35a1 1 0 0 0 0 1.302l4.843 5.65A2 2 0 0 0 6.603 15h7.08a2 2 0 0 0 2-2V3zM5.829 5.854a.5.5 0 1 1 .707-.708l2.147 2.147 2.146-2.147a.5.5 0 1 1 .707.708L9.39 8l2.146 2.146a.5.5 0 0 1-.707.708L8.683 8.707l-2.147 2.147a.5.5 0 0 1-.707-.708L7.976 8 5.829 5.854z"/>
                </svg>
                Назад</a>
        </div>
        </nav>




            <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header">
                                <h3 class="text-center font-weight-light my-4">Спасибо за заказ!</h3>
                            </div>
                            <div class="card-body text-center">
                                <h4>
                                    Ваш заказ успешно сформирован.
                                </h4>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>

{% endblock %}