cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),

    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

djangosite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from orders.views import stripe_webhook_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from main.views import basket_add, product_list, basket_remove


app_name = 'main'

urlpatterns = [

    path('', views.home_page, name='home_page'),

    path('product_list', product_list, name='product_list'),

    path('category/<int:category_id>/', product_list, name='category'),

    path('baskets/add/<int:product_id>/', basket_add, name='basket_add'),

    path('baskets/remove/<int:basket_id>/', basket_remove, name='basket_remove'),

    path('<int:id>/<slug:slug_category>/', views.product_list,
         name='product_list_by_category'),

    path('<int:id>/<slug:slug>', views.product_detail,
         name='product_detail'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from orders.views import OrderCreateView, SuccessTemplateView, CanceledTemplates, OrderListView, OrderDetailView


app_name = 'orders'

urlpatterns = [

    path('', OrderListView.as_view(), name='orders_list'),
    path('order-create/', OrderCreateView.as_view(), name='order_create'),
    path('order-success/', SuccessTemplateView.as_view(), name='order_success'),
    path('order_cancel/', CanceledTemplates.as_view(), name='order_cancel'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order'),




]

users/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from users.views import login, UserRegistrationView, UserProfileView, logout
from django.contrib.auth.views import LogoutView
from django.urls import path


app_name = 'users'



urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path('profile/<int:pk>/', UserProfileView.as_view(), name='profile'),
    path('logout/', logout, name='logout'),


]

main/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from users.models import User
import stripe



stripe.api_key = settings.STRIPE_SECRET_KEY


class Category(models.Model):
    name_category = models.CharField(max_length=100, db_index=True)
    slug_category = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('name_category',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        index_together = (('id', 'slug_category'),)

    def __str__(self):
        return self.name_category

    def get_absolute_url(self):
        return reverse('main:product_list_by_category', args=[self.id, self.slug_category])


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)

    name_product = models.CharField(max_length=150, db_index=True)
    slug = models.CharField(max_length=150, db_index=True, unique=True)
    image_product = models.ImageField(upload_to='product/%Y/%m/%d', blank=True)
    description_product = models.TextField(max_length=1000, blank=True)
    price_product = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    uploaded = models.DateTimeField(auto_now=True)
    stripe_product_price_id = models.CharField(max_length=150, null=True, blank=True)
    quantity = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ('name_product',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        index_together = (('id', 'slug'),)

    def __str__(self):
        return f'Продукт: {self.name_product} | Категория: {self.category.name_category}'

    def get_absolute_url(self):
        return reverse('main:product_detail', args=[self.id, self.slug])


    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.stripe_product_price_id:
            stripe_product_price = self.create_stripe_product_price()
            self.stripe_product_price_id = stripe_product_price['id']
        super(Product, self).save(force_insert=False, force_update=False, using=None, update_fields=None)

    def create_stripe_product_price(self):
        stripe_product = stripe.Product.create(name=self.name_product)
        stripe_product_price = stripe.Price.create(
            product=stripe_product['id'], unit_amount=round(self.price_product * 100), currency="rub"
        )
        return stripe_product_price


class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        return sum(basket.sum() for basket in self)

    def total_quantity(self):
        return sum(basket.quantity for basket in self)

    def stripe_products(self):
        line_items = []
        for basket in self:
            item = {
                'price': basket.product.stripe_product_price_id,
                'quantity': basket.quantity,
            }
            line_items.append(item)
        return line_items


class Basket(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    objects = BasketQuerySet.as_manager()

    def __str__(self):
        return f'Корзина для {self.user.username} | Продукт: {self.product.name}'

    def sum(self):
        return self.product.price_product * self.quantity

    def de_json(self):
        basket_item = {
            'product_name': self.product.name_product,
            'quantity': self.quantity,
            'price': float(self.product.price_product),
            'sum': float(self.sum()),
        }
        return basket_item

    @classmethod
    def create_or_update(cls, product_id, user):
        baskets = Basket.objects.filter(user=user, product_id=product_id)

        if not baskets.exists():
            obj = Basket.objects.create(user=user, product_id=product_id, quantity=1)
            is_created = True
            return obj, is_created
        else:
            basket = baskets.first()
            basket.quantity += 1
            basket.save()
            is_crated = False
            return basket, is_crated

main/views.py
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required

from django.shortcuts import render, get_object_or_404

from .models import Category, Product, Basket
from cart.forms import CartAddProductForm

from users.models import User



def product_list(request, category_slug=None, category_id=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(category_id=category_id) if category_id else Product.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'main/product/list.html',
                  {
                      'category': category,
                      'categories': categories,
                      'products': products
                  })




def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'main/product/detail.html', {'product': product,
                                                        'cart_product_form': cart_product_form})


def home_page(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'main/product/index.html',
                  {
                      'category': category,
                      'categories': categories,
                      'products': products
                  })


@login_required
def basket_add(request, product_id):
    product = Product.objects.get(id=product_id)
    basket = Basket.objects.filter(user=request.user, product=product)

    if not basket.exists():
        Basket.objects.create(user=request.user, product=product, quantity=1)
    else:
        basket = basket.first()
        basket.quantity += 1
        basket.save()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

main/templates/main/product/base.html
{% load static %}
<!DOCTYPE html>
<html>

<title>
    {% block title %} {% endblock %}
</title>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Store</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
            crossorigin="anonymous"></script>
    <link href="npm i bootstrap-icons" rel="stylesheet">


    <nav class="navbar" style="background-color: #ffc107;">
        <div class="container-fluid">
                <a class="container-fluid" href="{% url 'main:home_page' %}">
            <img src="{% static 'main/img/Logo.png' %}" alt="connect" style="max-height:70px"></a>
        </div>
    </nav>

</head>
{#<a class="btn btn-dark mx-2" href="{% url 'main:home_page' %}" role="button">#}

<div id="content">
    {% block content %} {% endblock %}
</div>


<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <hr style="border-style: dashed;">
                <p>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-c-circle-fill" viewBox="0 0 16 16">
                        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0ZM8.146 4.992c.961 0 1.641.633 1.729 1.512h1.295v-.088c-.094-1.518-1.348-2.572-3.03-2.572-2.068 0-3.269 1.377-3.269 3.638v1.073c0 2.267 1.178 3.603 3.27 3.603 1.675 0 2.93-1.02 3.029-2.467v-.093H9.875c-.088.832-.75 1.418-1.729 1.418-1.224 0-1.927-.891-1.927-2.461v-1.06c0-1.583.715-2.503 1.927-2.503Z"/>
                    </svg>
                    Company, 2023
                </p>
            </div>
        </div>
    </div>
</footer>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js"
        integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js"
        integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ"
        crossorigin="anonymous"></script>
</body>
</html>

main/templates/main/product/detail.html
{% extends "main/product/base.html" %}
{% load static %}

{% block title %}
    {{ product.name_product }}
{% endblock %}

{% block content %}
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet"/>

    {#    ВЕРХНЯЯ ЧАСТЬ ПОД ШАПКОЙ#}
    <nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
        <div class="container-fluid">

            {#            КНОПКА НАЗАД#}
            <a class="btn btn-dark mx-2 my-2" href="{% url 'main:home_page' %}" role="button">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-backspace-fill" viewBox="0 0 16 16">
                    <path d="M15.683 3a2 2 0 0 0-2-2h-7.08a2 2 0 0 0-1.519.698L.241 7.35a1 1 0 0 0 0 1.302l4.843 5.65A2 2 0 0 0 6.603 15h7.08a2 2 0 0 0 2-2V3zM5.829 5.854a.5.5 0 1 1 .707-.708l2.147 2.147 2.146-2.147a.5.5 0 1 1 .707.708L9.39 8l2.146 2.146a.5.5 0 0 1-.707.708L8.683 8.707l-2.147 2.147a.5.5 0 0 1-.707-.708L7.976 8 5.829 5.854z"/>
                </svg>
                Назад</a>

            {#            ВОЙТИ#}
            <div class="row ">
                <div class="col-sm-5">
                    {% if user.is_authenticated %}
                        <div class="btn-group dropstart">
                            <button type="button" class="btn btn-dark dropdown-toggle dropdown-toggle-split"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                <span class="visually-hidden"></span>
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>
                                    <a class="dropdown-item" href="{% url 'users:profile' user.id %}">Профиль</a>
                                </li>
                                <li><a class="dropdown-item" href="{% url 'orders:orders_list' %}">Заказы</a></li>
                                {% if user.is_superuser or user.is_staff %}
                                    <li>
                                        <a class="dropdown-item" href="{% url 'admin:index' %}">
                                            Админ-панель
                                        </a>
                                    </li>
                                {% endif %}
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'users:logout' %}">
                                        Выйти
                                    </a>
                                </li>
                            </ul>
                            <button type="button" class="btn btn-warning">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-person-circle" viewBox="0 0 16 16">
                                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                                    <path fill-rule="evenodd"
                                          d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                                </svg>
                            </button>
                            {#    КОРЗИНА#}
                            <button type="button" class="btn btn-warning mx-2">
                                <a class="dropdown-item" href="{% url 'users:profile' user.id %}">Корзина</a>

                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-cart-fill" viewBox="0 0 16 16">
                                    <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                                </svg>
                            </button>


                            {% else %}

                            <a class="nav-link " href="{% url 'users:login' %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-box-arrow-in-right" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd"
                                          d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0v-2z"/>
                                    <path fill-rule="evenodd"
                                          d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
                                </svg>
                                Войти <i class="fas fa-sign-in-alt"></i></a>
                        </div>
                    {% endif %}

                </div>
            </div>

        </div>
    </nav>

    {#    КОНЕЦ ВЕРХНЕЙ ЧАСТИ ПОД ШАПКОЙ#}


    <div class="container-fluid">
        <div class="card mb-3" style="max-width: 2500px;">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="{{ product.image_product.url }}" class="img-fluid rounded-start" alt="...">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h4 class="card-title">{{ product.name_product }}</h4>
                        <p class="card-text">{{ product.description_product }}</p>
                        <h6><a>{{ product.category }}</a></h6>

                        <h5> <p class="price">{{ product.price_product }} руб. </p></h5>

                        <a class="btn btn-warning"
                           href="{% url 'main:basket_add' product.id %}">
                            Отправить в корзину
                        </a>


                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/product/list.html
{% extends "main/product/base.html" %}
{% load static %}



{% block title %}
    {% if category %}{{ category.name_category }}{% else %}Каталог{% endif %}
{% endblock %}


{% block content %}
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet"/>


    {#    ВЕРХНЯЯ ЧАСТЬ ПОД ШАПКОЙ#}
    <nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
        <div class="container-fluid">

            {#            КНОПКА НАЗАД#}
            <a class="btn btn-dark mx-2 my-2" href="{% url 'main:home_page' %}" role="button">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-backspace-fill" viewBox="0 0 16 16">
                    <path d="M15.683 3a2 2 0 0 0-2-2h-7.08a2 2 0 0 0-1.519.698L.241 7.35a1 1 0 0 0 0 1.302l4.843 5.65A2 2 0 0 0 6.603 15h7.08a2 2 0 0 0 2-2V3zM5.829 5.854a.5.5 0 1 1 .707-.708l2.147 2.147 2.146-2.147a.5.5 0 1 1 .707.708L9.39 8l2.146 2.146a.5.5 0 0 1-.707.708L8.683 8.707l-2.147 2.147a.5.5 0 0 1-.707-.708L7.976 8 5.829 5.854z"/>
                </svg>
                Назад</a>

            {#            ВОЙТИ#}
            <div class="row ">
                <div class="col-sm-5">
                    {% if user.is_authenticated %}
                        <div class="btn-group dropstart">
                            <button type="button" class="btn btn-dark dropdown-toggle dropdown-toggle-split"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                <span class="visually-hidden"></span>
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>
                                    <a class="dropdown-item" href="{% url 'users:profile' user.id %}">Профиль</a>
                                </li>
                                <li><a class="dropdown-item" href="{% url 'orders:orders_list' %}">Заказы</a></li>
                                {% if user.is_superuser or user.is_staff %}
                                    <li>
                                        <a class="dropdown-item" href="{% url 'admin:index' %}">
                                            Админ-панель
                                        </a>
                                    </li>
                                {% endif %}
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'users:logout' %}">
                                        Выйти
                                    </a>
                                </li>
                            </ul>
                            <button type="button" class="btn btn-warning">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-person-circle" viewBox="0 0 16 16">
                                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                                    <path fill-rule="evenodd"
                                          d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                                </svg>
                            </button>
                            {#    КОРЗИНА#}
                            <button type="button" class="btn btn-warning mx-2">
                                <a class="dropdown-item" href="{% url 'users:profile' user.id %}">Корзина</a>

                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-cart-fill" viewBox="0 0 16 16">
                                    <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                                </svg>
                            </button>

                            {% else %}

                            <a class="nav-link " href="{% url 'users:login' %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-box-arrow-in-right" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd"
                                          d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0v-2z"/>
                                    <path fill-rule="evenodd"
                                          d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
                                </svg>
                                Войти <i class="fas fa-sign-in-alt"></i></a>
                        </div>
                    {% endif %}

                </div>
            </div>
    </nav>

    {#    КОНЕЦ ВЕРХНЕЙ ЧАСТИ ПОД ШАПКОЙ#}


    {#    МЕНЮ#}
    <button class="tablink"><a href="{% url 'main:product_list' %}" class="list-group-item">Все категории</a></button>
    {% for categor in categories %}
        <button class="tablink"><a href="{% url 'main:category' categor.id %}"
                                   class="list-group-item">{{ categor.name_category }}</a></button>
    {% endfor %}
    {#КОНЕЦ МЕНЮ#}


    <div class="container">
        <div class="row">
            {% for product in products %}
                <div class="col-lg-4 col-sm-6">
                    <div class="product-card">
                        <div class="product-thumb">
                            <a href="{{ product.get_absolute_url }}">
                                <img src=" {% if product.image_product %}{{ product.image_product.url }}
                                    {% else %}{% static 'img/no_image.png' %}{% endif %}">
                            </a>
                        </div>
                        <div class="product-details">
                            <h4><a href="{{ product.get_absolute_url }}">{{ product.name_product }}</a></h4>
                            <p><a href="{{ product.get_absolute_url }}">{{ product.description_product }}</a></p>
                        </div>
                        <div class="product-bottom-details d-flex justify-content-between">
                            <div class="product-price">
                                <button type="button" class="btn btn-warning text-dark"><a
                                        href="{{ product.get_absolute_url }}">{{ product.price_product }} руб.</a>
                                </button>
                                <button type="button" class="btn btn-warning text-dark"><a
                                        href="{% url 'main:basket_add' product.id %}">В корзину</a>
                                </button>

                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

    </div>


{% endblock %}